server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/homepage?useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=GMT
    username: root
    password: zan940128
    driver-class-name: com.mysql.jdbc.Driver
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.aerothief.model  # 注意：对应实体类的路径
#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check

#md5加密盐值
MD5Sult: 31&^^$%&BSD":>}{}"|